# What items are shown on the dashboard?
STAT_TABLES = [
    'games', 
    'goals', 
    'fouls', 
    'lineups', 
    'stats', 
    'standings', 
    'bios',
    'awards',
    ]

SOURCES = [
    'small',
    'melvin',
    'tours',
    'state',
    'american_cup',
    'open_cup',
    'nafbl',
    'asl',
    'esl',
    'lewis_cup',
    'asl2',
    'isl',
    'indoor',
    'nasl',
    'apsl',
    'usl',
    'usl_leach',
    'misl',
    'mls',
    'mls_playoffs',
    'mls_soccernet',
    'mls_reserve',
    'ussf2',
    'nasl2',
    'city',
    'ncaa',
    #'world_cup',
    'concacaf',
    'mexico',
    'usa',
    'fifa',
        ]

# Skipping these.
l =    [ 
        'uslsoccer',
        'wiki',
        'kicker',
        'mediotiempo',
        'cnnsi',
        'eufootball',
        ]


SINGLE_SOURCES = [
    'sources',
    'countries',
    'states',
    'state_populations',
    'cities',
    'stadiums', 
    'salaries',
    'competitions',
    'teams', 
    'bios', 
    'awards', 
    'drafts',
    'picks',
    'positions', 
    'name_maps', 
    'stadium_maps', 
    'competition_maps', 
    'news',
    'prerosters',
    ]
