#!/usr/local/bin/env python
# -*- coding: utf-8 -*-


names = {

    'Joseph (Joey) Johnson': 'Joey Johnson',
    'Leon (Kacy) Jones': 'Leon Jones',


    'Walter Czyzowych': 'Walter Chyzowych',
    'Walt Czychowych': 'Walter Chyzowych',
    'Walt Chyzowych': 'Walter Chyzowych',


    'Richard (Rich) Bradley': 'Richard Bradley',
    'William (Brad) Moore': 'Brad Moore',
    'William Moore': 'Brad Moore',

    'Laurence (Lloyd) Holder': 'Laurence Holder',
    'William (Will) Hench': 'William Hench',
    'Lester (Les) Lunsford': 'Les Lunsford',
    'Lester Lunsford': 'Les Lunsford',
    'Lyndon (Nigel) Burgess': 'Lyndon Burgess',
    'Guillermo (Memo) Medina': 'Guillermo Medina',
    'Ricardo (Ricky) Blanchard': 'Ricardo Blanchard',
    'Ricky Blanchard': 'Ricardo Blanchard',
    'Charles (Chuck) Panos': 'Charles Panos',
    'Kryszyof (Chris) Legowski': 'Chris Legowski',
    'Kyle (Lighty) Lightbourne': 'Kyle Lightbourne',
    'Rolando Aguilera': 'Roland Aguilera',
    'Edward (Eddie) Child': 'Edward Child',
    'Teodor (Marcel) Matis': 'Marcel Matis',
    'James (Troy) Garner': 'Troy Garner',
    'James Garner': 'Troy Garner',
    'William (B.J.) McNicol': 'William McNicol',
    'B.J. McNicol': 'William McNicol',
    'BJ McNicol': 'William McNicol',
    'Stephen (Kelly) Findley': 'Kelly Findley',
    'Jose (Alex) Matturro': 'Alex Matturro',
    'Malcolm (Sean) Endicott': 'Sean Endicott',
    'Robert (Justin) Kerns': 'Robert Kerns',
    'Michael (Gabe) Jones': 'Gabe Jones',
    'Iyoma (Jo Jo) Flemister': 'Iyoma Flemister',
    'Thomas (Michael) Coll': 'Michael Coll',
    
    'J Cooks': 'Judah Cooks', # Highly likely, NVA Royals game in 2000, while Judah was with DC
    'Joseph (Joe) Nick': 'Joe Nick',
    

    
    
    
    
    'Richard (Cody) Bragg': 'Richard Bragg',
    'Benjamin (Ben) Meek': 'Benjamin Meek',

    'John (Jack) Cummings': 'Jack Cummings',

    'Terrance (Terry) McNelis': 'Terrance McNelis',
    'Terry McNelis': 'Terrance McNelis',
    'Stephen (Ste) Astwood': 'Stephen Atwood',

    'Collin (CJ) Robinson': 'C.J. Robinson',
    
    'Bret (Eric) Jones': 'Bret Jones',
    'Miguel (Kiko) Medina': 'Miguel Medina',
    'Devaun (Sammy) DeGraff': 'Devaun DeGraff',
    'Daniel (Dan) Hartung': 'Daniel) Hartung',

    'Joseph (Joe) McNab': 'Joseph McNab',
    'Juvenal (Junior) Zarate': 'Juvenal Zarate',
    'Jean (Robens) Jerome': 'Jean-Robens Jermoe',
    'Jean Jerome': 'Jean-Robens Jermoe',

    'Vincente (Vinny) Bastidas': 'Vincente Bastidas',
    'Vincent Bastidas': 'Vincente Bastidas',

    'Michael (Mick) McDermott': 'Michael McDermott',
    'Theodore (Ted) Haley': 'Ted Haley',
    'Adetoye (Toye) Oshoniyi': 'Adetoye Oshoniyi',
    'Toye Oshoniyi': 'Adetoye Oshoniyi',

    'Joseph (JoJo) Stuart': 'Jojo Stuart',
    
    'Michael (Mike) Franks': 'Michael Franks',
    'Mike Franks': 'Michael Franks',
    'Robert (Rob) Fucci': 'Robert Fucci',
    'Kristofer (Kris) Larsen': 'Kristofer Larsen',
    'Christopher (Klotzy) Klotz': 'Christopher Klotz',

    
    


    'Robert Alexander': 'Trey Alexander',
    'Robert (Trey) Alexander': 'Trey Alexander',

    'Roberto Brown': 'Roberto Ronaldo Brown Perea',
    'Joel (JJ) Bailey': 'Joel Bailey',
    'Gason (Bubbla) Gregory': 'Gason Gregory',

    'James Hood': 'Jimmy Hood',

    'Benjamin (Ben) Hill': 'Benjamin Hill',
    'Benjamin (Ben) Meek': 'Benjamin Meek',
    'Emanuel (Manny) Brito': 'Emanuel Brito',
    'Angel (Christopher) Rivillo': 'Angel Rivillo',



    'Carl Calentine': 'Carl Valentine',
    'Carlos Mendez': 'Carlos Mendes',

    'Loyd Barker': 'Lloyd Barker',
    'Greg (Chevy) Chevalier': 'Greg Chevalier',
    'Andy Parrish': 'Andrew Parrish',
    'Jim Manganello': 'James Manganello',
    'Charles Brown': 'C.J. Brown',
    'Jose Vasquez': 'Joseph Vasquez-Martinez',
    'Brian Taylor': 'Bryan Taylor',
    'Jacob Joy': 'Jake Joy',
    'Jacob (Jake) Joy': 'Jake Joy',
    'Kyle Marten Altman': 'Kyle Altman',
    'Michael Feniger': 'Mike Feniger',
    'Julian Dorsey': 'JT Dorsey',
    'Tom Wurdack': 'Thomas Wurdack',
    'Staale Soebye': 'Ståle Søbye',
    'Matthew Nwabueze Okoh': 'Matt Okoh',
    'Thomas (Tommy) Tanner': 'Thomas Tanner',
    'Williams Sedgewick': 'Bill Sedgewick',
    'William (Bill) Sedgewick': 'Bill Sedgewick',
    'Williams (Bill) Sedgewick': 'Bill Sedgewick',
    'Andrew (Yogi) McKay': 'Andrew McKay',
    'Yogi McKay': 'Andrew McKay',

    'Edivaldo Da Silva-Sarafim Jr': 'Edivaldo Sarafim-DaSilva',
    'Edivaldo (Juninho) Sarafim-DaSilva': 'Edivaldo Sarafim-DaSilva',
    'Edivaldo (Juninho) Sarafim-DaSilva': 'Edivaldo Sarafim-DaSilva',
    'Edivaldo Da Silva-Sarafim Jr': 'Edivaldo Sarafim-DaSilva',

    
    'Gabriel Valencia-Jiminez': 'Gabriel Valencia-Jimenez',
    'Aaran (Kiwi) Lines': 'Aaran Lines',
    'Abiodun (Mike) Adeyemi': 'Abiodun Adeyemi',
    'Alejandro (Jano) Gonzalez': 'Alejandro Gonzalez Pareja',
    'Alejandro Gonzalez-Pareja': 'Alejandro Gonzalez Pareja',
    'Alexander Delgado-Marques': 'Alexander Marques-Delgado',
    'Angel Rivillo-Ruiz': 'Angel Rivillo',
    'Carlos Garcia': 'Carlos Garcia-Dominguez',
    'Chris Da Silva': 'Chris DaSilva',
    'Chris Hooser': 'Chris Houser',
    'Chris Rozelli': 'Chris Roselli',
    'Christopher Bagley': 'Chris Bagley',
    'Christopher Brown': 'Chris Brown',
    'Christopher Brunt': 'Chris Brunt',
    'Christopher Corcoran': 'Chris Corcoran',
    'Christopher Doyle': 'Chris Doyle',
    'Christopher Kooy': 'Chris Kooy',
    'Christopher Lemons': 'Chris Lemons',
    'Christopher Martinez': 'Chris Martinez',
    'Christopher Pozniak': 'Chris Pozniak',
    'Christopher Seitz': 'Chris Seitz',
    'Christopher Wanamaker': 'Chris Wanamaker',
    'Christopher Williams': 'Chris Williams',
    'Crizam (Zinho) Oliveira': 'Crizam César de Oliveira Filho',
    'Crizam (Zinho) Oliveira-Filho': 'Crizam César de Oliveira Filho',
    'Damon Kensing': 'Damon Rensing',
    'Daniel Benton': 'Dan Benton',
    'Daniel Earls': 'Danny Earls',
    'Daniel Keith Earls': 'Danny Earls',
    'Daniel Sindui': 'Daniel Singhui',
    'Danley Hjohnson': 'Danley Johnson',
    'Didar Sandttu': 'Didar Sandhu',
    'Dominic Mobilio': 'Domenic Mobilio',
    'Dustin Hudock': 'Dusty Hudock',

    'Frankie Sanfilippo': 'Frank Sanfillippo',
    'Frankie Sanfillippo': 'Frank Sanfillippo',
    'Gregory Simmonds': 'Greg Simmonds',
    'Gregory Sutton': 'Greg Sutton',
    'Guy Vallcourt': 'Guy Valcourt',
    'Isaac (Saito) Nieves': 'Isaac Nieves-Rivera',
    'Jim Welsh': 'Jim Welch',
    'Joel (JJ) Bailey': 'Joel Bailey',
    'Joe Seigliano': 'Joe Scigliano',
    'Joesph McNab': 'Joseph McNab',
    'John (Alvin) Hudson': 'John Hudson',
    'John Cariel': 'John Cairel',
    'John Jones Ii': 'John Jones II',
    'Zacharias Scott': 'Zach Scott',
    'Zachary (Zach) Kirby': 'Zachary Kirby',
    'Zach Kirby': "Zachary Kirby",
    'Jonathan (Jonny) Steele': 'Jonathan Steele',
    'Jose Roberto Gomes Santana': 'Jose Roberto Santana',
    'Marvin Quisano': 'Marvin Quijano',
    'Matt Botgard': 'Matt Borgard',
    'Matthew (Deli) Delicâte': 'Matthew Delicâte',
    'Matthew Delicate': 'Matthew Delicâte',
    'Mobi Obaraku': 'Mobi Oparaku',
    'Rey (Boom Boom) Martinez': 'Rey Angel Martinez',
    'Rey Martinez': 'Rey Angel Martinez',
    'Richard Gilstrap': 'Hunter Gilstrap',
    'Richard Hunter Gilstrap': 'Hunter Gilstrap',
    'Robert (Shea) Salinas': 'Shea Salinas',
    'Srdjan (Serge) Djekanovic': 'Srdjan Djekanović',
    'Tenywa (T-Bone) Bonseu': 'Tenywa Bonseu',
    'Thomas (John) Queeley': 'Thomas Queeley',
    'Thomas Poltl': 'Tom Poltl',
    'Umbertino (Tino) Cucca': 'Umbertino Cucca',
    'Umbertino Cucck': 'Umbertino Cucca',
    'Wendell Nuldron': 'Wendell Muldrow',

    'Abbey Hoibi': 'Abbey Noibi',

    'Adetoye (Toye) Oshoniyi': 'Adetoye Oshoniyi',
    'Adloye Oshoniyi': 'Adetoye Oshoniyi',
    'Adloye (Toye) Oshoniyi': 'Adetoye Oshoniyi',
    'Adrian (Piticu) Bumbut': 'Adrian Bumbut',
    'Baboy Goye': 'Babou Gaye',
    'Emeke Moneme': 'Emeka Moneme',
    'Gerhard (Kirk) Freidrich': 'Gerhard Friedrich',
    'Kirk Friedrich': 'Gerhard Friedrich',
    'Geroge (Mike) Brown': 'George (Mike) Brown',
    'Victor Pasacci': 'Victor Passucci',

    'David (Hunter) Paschall': 'David Paschall',
    'Francis (Fran) Morgan': 'Francis Morgan',
    
    

    
    
    


    'pk': 'penalty kick',
    'PK': 'penalty kick', 

    'Own goal': 'Own Goal',


    # Staging
    'Scott Nilsen': 'Werner Nilsen',


    # Make sure these work.
    'Maclean': 'MacLean',
    'O’Boyle': 'O\'Boyle',
    'O’Hara': 'O\'Hara',
    'Brian O’Haver': 'Brian O\'Haver',
    'John O’Connell': 'John O\'Connell',
    'Jack O’Reilly': 'Jack O\'Reilly',
    'Victor Estupiñan': 'Víctor Estupiñán',
    'Victor Estupiñán': 'Víctor Estupiñán',


    'Pavel Pardo': 'Pável Pardo',
    'Tomas Boy': 'Tomás Boy',
    'Lothar Matthaus': 'Lothar Matthäus',
    'Ramon Ramirez': 'Ramón Ramírez',
    'Juan Pablo Garcia': 'Juan Pablo García',

    'Raul Lara': 'Raúl Lara',
    'Juan Manuel Pena': 'Juan Manuel Peña',
    'Eddie Skiba': 'Ed Skiba',
    'Joey Boyle': 'Joe Boyle',
    'Jackie Hynes': 'Jack Hynes',

    'Jesus Mendoza': 'Jesús Mendoza',
    'Diego Martinez': 'Diego Martínez',
    'Jesus Padilla': 'Jesús Padilla',
    'Luis Garcia': 'Luis García',
    'Vitor Baia': 'Vítor Baía',

    'Arturo Alvarez': 'Arturo Álvarez',
    'Oscar Sanchez': 'Óscar Sánchez',
    'Benjamin Galindo': 'Benjamín Galindo',
    'Victor Cordero': 'Víctor Cordero',
    'Ignacio Ambriz': 'Ignacio Ambríz',
    
    'Claudio Lopez': 'Claudio López',

    'Adolfo Rios': 'Adolfo Ríos',
    'Andreas Moller': 'Andreas Möller',

    'Joao Vieira Pinto': 'João Vieira Pinto',

    

    'Taifour Diane': 'Taifour Diané',

    'Esse Baharmast': 'Esfandiar Baharmast',

    'Benedict Iroha': 'Ben Iroha',
    'Uchenna Okafor': 'Uche Okafor',
    'Bennie McCarthy': 'Benni McCarthy',
    'Benedict McCarthy': 'Benni McCarthy',

    'Carsten Sirsbaeck': 'Carsten Sirsbaek',

    'Billy Herd': 'Willie Herd',
    'David Brown': 'Davey Brown',
    'Tom Florie': 'Tommy Florie',
    'Cyril Irving Davis': 'Irving Davis',
    'Henry Meyerdirks': 'Henry Meyerdierks',
    'Tom MacFarlane': 'Tommy McFarlane',
    'Rabbit Heminsley': 'Rabbit Hemingsley',
    'John Hemingsley': 'Rabbit Hemingsley',
    'Philip Slone': 'Phil Slone',
    'Alexander Rae': 'Alex Rae',
    'Frantisek Sedlacek': 'Ferenc Szedlacsek',
    'Hans Tandler': 'Johann Tandler',
    'Harry Oellerman': 'Dutch Oellerman',

    'John Kerr': 'John Kerr Jr.',
    'Bill Crook': 'Billy Crook',
    'Emmanuel (Manny) Oudin': 'Manny Oudin',
    'Manny Oidin': 'Manny Oudin',
    'Emmanual Oudin': 'Manny Oudin',
    'Paul Moylan': 'Archie Moylan',
    'Paul (Archie) Moylan': 'Archie Moylan',
    'Dionysus Sebwe': 'Dionysius Sebwe',
    'Josh McKay': 'Joshua McKay',


    'Jose Diaz': 'José Díaz',
    'Ryan  Cordeiro': 'Ryan Cordeiro',
    'Gabbo Gavric': 'Momcilo Gavrić',
    'Kai Haaskavi': 'Kai Haaskivi',
    'Luis Perez': 'Luis Pérez',
    'David Junior Lopes': 'David Júnior Lopes',
    'Cesar Delgado': 'César Delgado',
    'Jose Gomez': 'José Gómez',
    'Fernando Gonzalez': 'Fernando González',
    'Saul Martinez': 'Saúl Martínez',
    'Sergio Perez': 'Sergio Pérez',
    'Juan Garcia': 'Juan García',
    'Gary Delong': 'Gary DeLong',
    'Hugo Perez': 'Hugo Pérez',
    'Cesar Villaluz': 'César Villaluz',
    'Diego Jimenez': 'Diego Jiménez',
    'Julian De Guzman': 'Julian de Guzman',
    'Saidi Isaac': 'Saïdi Isaac',
    'Carlos Pavon': 'Carlos Pavón',
    'Argenis Fernandez': 'Argenis Fernández',
    'Elias Montes': 'Elías Montes',
    'Carlos Hernandez': 'Carlos Hernández',
    'Yordany Alvarez': 'Yordany Álvarez',
    'Carlos Mejia': 'Carlos Mejía',
    'Jose Francisco Torres': 'José Francisco Torres',

    



    'S.Benedetti': 'Scott Benedetti',
    'B.Namoff': 'Bryan Namoff',
    'B.Arena': 'Bruce Arena',
    'C.Onalfo': 'Curt Onalfo',
    'Z.Wells': 'Zach Wells',
    'A.Eskandarian': 'Alecko Eskandarian',
    'G.Cameron': 'Geoff Cameron',
    'J.Enochs': 'Joe Enochs',
    'T.Chronopoulos': 'Ted Chronopoulos',
    'C.Wingert': 'Chris Wingert',
    'P.Holocher': 'Paul Holocher',
    'C.Simms': 'Clyde Simms',
    'J.Gros': 'Josh Gros',
    'G.Agbossoumonde': 'Gale Agbossoumonde',
    'D.Yelldell': 'David Yelldell',
    'C.Barrett': 'Chad Barrett',
    'M.Cozier': 'Mac Cozier',
    'J.Busch': 'Jon Busch',
    'C.Clark': 'Colin Clark',
    'S.Zizzo': 'Sal Zizzo',
    'I.Baba': 'Imad Baba',
    'C.McCarty': 'Chad McCarty',
    'M.Huseinovic': 'Mirsad Huseinovic',
    'T.Presthus': 'Tom Presthus',
    'L.Robles': 'Luis Robles',
    'J.Franchino': 'Joe Franchino',
    'U.Ihemelu': 'Ugo Ihemelu',
    'T.Dunivant': 'Todd Dunivant',
    'P.Vagenas': 'Peter Vagenas',
    'J.Marsch': 'Jesse Marsch',
    'unk.DiCicco': 'Tony DiCicco',
    'J.Pollihan': 'Jim Pollihan',
    'P.Millar': 'Peter Millar',
    'C.McCully': 'Charlie McCully',
    'M.Ivanow': 'Mike Ivanow',
    'A.Skotarek': 'Alex Skotarek',
    'D.Albrecht': 'Dietrich Albrecht',
    'J.Mapp': 'Justin Mapp',
    'A.Aly': 'Amr Aly',
    'J.Durgan': 'Jeff Durgan',
    'B.West': 'Brian West',
    'H.Wecke': 'Herman Wecke',
    'S.Formoso': 'Santiago Formoso',
    'M.Peterson': 'Mark Peterson',
    'G.DeLong': 'Gary DeLong',
    'V.Gerley': 'Victor Gerley',
    'A.Mayer': 'Alan Mayer',
    'P.Gyau': 'Philip Gyau',
    'Y.Allnutt': 'Yari Allnutt',
    'H.Bicek': 'Helmut Bicek',
    'E.Clear': 'Eddie Clear',
    'F.Simek': 'Frank Simek',
    'E.Radwanski': 'Ed Radwanski',
    'T.Snyder': 'Troy Snyder',
    'D.Ervine': 'Dale Ervine',
    'Z.Snylyk': 'Zenon Snylyk',
    'P.Matevich': 'Pete Matevich',
    'P.Bravo': 'Paul Bravo',
    'Y.Chacurian': 'Efraim Chacurian',
    'Corn.Casey': 'Cornelius Casey',
    'R.Hornberger': 'Raymond Hornberger',
    'N.Vargas': 'Nelson Vargas',
    'B.Mahy': 'Barry Mahy',
    'E.Comrie': 'Elvis Comrie',
    'D.Hall': 'Dick Hall',
    'J.Hynes': 'Jack Hynes',
    'A.Hamlyn': 'Alan Hamyln',
    'D.Malinowski': 'Donald Malinowski',
    'B.Benedict': 'Brian Benedict',
    'A.Domingues': 'Altino Domingues',
    'W.Ziaja': 'Wally Ziaja',
    'F.O\'Connor': 'Fred O\'Conner',
    'A.Rae': 'Alexander Rae',
    'J.McEwan': 'John McEwan',
    'G.Nemchick': 'George Nemchik',
    'M.Rys': 'Miro Rys',
    'D.Lawson': 'Doc Lawson',
    'S.Shafer': 'Stefan Szefer',
    'M.Brady': 'Michael Brady',
    'E.Castillo': 'Edgar Castillo',
    'L.Cullen': 'Leo Cullen',
    'J.Dubienny': 'John Dubienny',
    'S.Feher': 'Sandy Feher',
    'W.Freitag': 'Willy Freitag',
    'P.Chandler': 'Peter Chandler',
    'J.Dunn': 'Jason Dunn',
    'J.Ferreira': 'Joe Ferreira',
    'H.Knight': 'Hayden Knight',
    'J.Speca': 'Joe Speca',
    'P.Woodring': 'Peter Woodring',
    'M.Jeffries': 'Mike Jeffries',
    'N.Jaqua': 'Nate Jaqua',
    'H.Wells': 'Herbert Wells',
    'A.Strouse': 'Andy Strouse',
    'J.Salcedo': 'Jorge Salcedo',
    'J.Michaels': 'Joseph Michaels',
    'B.Abaunza': 'Bayardo Abaunza',
    'T.Gillen': 'Ted Gillen',
    'J.Panek': 'Jerry Panek',
    'B.Straub': 'Bill Straub',
    'A.Papoulias': 'Andy Papoulias',
    'L.Nguyen': 'Lee Nguyen',
    'G.Tober': 'Gene Tober',
    'B.Boswell': 'Bobby Boswell',
    'M.Malizewski': 'Miguel Malizewski',
    'J.Martinelli': 'Joe Martinelli',
    'D.Coskunian': 'Dave Coskunian',
    'C.Ellis': 'Charles Ellis',
    'R.Kuntner': 'Rudy Kuntner',    
    'K.Fister': 'Carl Fister',
    'B.Wattman': 'Ben Wattman',
    'H.McCully': 'Henry McCully',
    'C.Spalding': 'Dick Spalding',
    
    

    'AJ Soares': 'A.J. Soares',
    'AJ DeLaGarza': 'A.J. DeLaGarza',
    'Ashley Mcinnes': 'Ashley McInnes',
    'Brandon Mcdonald': 'Brandon McDonald',
    'CJ Brown': 'C.J. Brown',
    'Ciaran O\Brien': 'Ciaran O\'Brien',
    'DJ Countess': 'D.J. Countess',
    'Hamisi Amani-dove': 'Hamisi Amani-Dove',
    'Jay Demerit': 'Jay DeMerit',
    'John Van Buskirk': 'John van Buskirk',
    'Joe Max Moore': 'Joe-Max Moore',
    'Keith Defini': 'Keith DeFini',
    'Leighton O\'brien': 'Leighton O\'Brien',
    'Riley O\'neill': 'Riley O\'Neill',
    'RJ Allen': 'R.J. Allen',
    'Todd Denault': 'Todd DeNault',

    'Jose Burciaga, Jr.': 'Jose Burciaga Jr.',
    'Ramon Nuñez': 'Ramón Núñez',
    'Ramon Núñez': 'Ramón Núñez',
    'Carlos Rodriguez': 'Carlos Rodríguez',
    'Orlando Perez': 'Orlando Pérez',
    'Rodrigo Lopez': 'Rodrigo López',
    'Hector Jimenez': 'Héctor Jiménez',
    'Francisco Gomez': 'Francisco Gómez',
    'Martin Nunez': 'Martin Nuñez',
    'Fabian Castillo': 'Fabián Castillo',

    'Hugo Perez': 'Hugo Pérez',
    'Diego Gutierrez': 'Diego Gutiérrez',
    'Herculez Gomez': 'Herculez Gómez',
    'Jose Torres': 'José Torres',
    
    
    


    'Alex Morfaw': 'Alexandre Morfaw',
    'Albert Munoz': 'Alberto Munoz',
    'Andrew Webber': 'Andrew Weber',
    'A. J. Soares': 'A.J. Soares',
    'Alex Prampin': 'Alan Prampin',
    'Antonio De La Torre': 'Antonio de la Torre',
    u'Abraham Fran\xe7ois': 'Abraham Francois',
    'Austin Da Luz': 'Austin da Luz',
    'AJ Wood': 'A.J. Wood',
    'ANDREW Mcdermott': 'Andrew McDermott',
    'Andrew Mcdermott': 'Andrew McDermott',
    u'\xc1lvaro Fern\xe1ndez': 'Alvaro Fernandez',
    u'Andr\xe9s Mendoza': 'Andres Mendoza',
    u'Alvaro Sabor\xedo': 'Alvaro Saborio',
    u'\xc1lvaro Sabor\xedo': 'Alvaro Saborio',
    'Alvaro Saborio': 'Álvaro Saborío',
    'Alexis (Pasa) Rivera': 'Alexis Rivera',
    'Alexis Rivera-Curet': 'Alexis Rivera',
    'Anthony McManus': 'Tony McManus',
    'Anthony (Tony) McManus': 'Tony McManus',
    'Andre Sherard': 'André Sherard',
    'Ali-John Utush': 'Ali John Utush',
    'Alijohn Utush': 'Ali John Utush',
    'Alvaro Saborio': 'Álvaro Saborío',
    'Alberto (Cuba) Delgado': 'Alberto Delgado',
    'Alan Mcloughlin': 'Alan McLoughlin',
    'Anthony De Avila': 'Anthony de Avila',
    'Adrian Paz': 'Adrián Paz',
    'Andrew Rosenband': 'Andy Rosenband',
    'Akeem Priestly': 'Akeem Priestley',
    'Antouman Jallow': 'Antou Jallow',
    'A. J. DeLaGarza': 'A.J. DeLaGarza',
    'AJ Jeffries': 'A.J. Jeffries',
    'Alex Pineda Chacon': 'Alex Pineda Chacón',
    'Abé Matamoros': 'Ábe Matamoros',
    'Abe Matamoros': 'Ábe Matamoros',
    'Alex Tobon Villa': 'Alex Tobon-Villa',
    'Andi Iro': 'Andy Iro',
    'Andy Gruenenbaum': 'Andy Gruenebaum',
    'AJ DeLaGarza': 'A.J. DeLaGarza',
    u'\xc1lvaro S\xe1nchez': 'Alvaro Sanchez',
    'Albert Celades': 'Alberto Celades',
    'A. J. Godbolt': 'A.J. Godbolt',
    'Andrew Hainault': 'André Hainault',
    'Andre Hainault': 'André Hainault',
    'Andy Mcmahon': 'Andy McMahon',
    u'Andr\xe9 Luiz': 'Andre Luiz',
    'Anthony Mckeon': 'Anthony McKeon',
    'Alex Pineda-Chacon': 'Alex Pineda Chacon',
    'Antonio De Avila': 'Antonio de Avila',
    'Bora Milutinovic': 'Bora Milutinović',
    'Bujon Vuckovic': 'Bojan Vuckovic',
    'Bo Vuckovic': 'Bojan Vuckovic',
    'Brian Namoff': 'Bryan Namoff',
    'Byran Namoff': 'Bryan Namoff',
    'Brad Mcglaughlin': 'Brad McGlaughlin',
    'Blair Gaven': 'Blair Gavin',
    'Bill Andracki': 'Billy Andracki',
    'Bryan Carroll': 'Brian Carroll',
    'Brandon Mcdonald': 'Brandon McDonald',
    'Brett Mcdermott': 'Brett McDermott',
    'Brian Mcbride': 'Brian McBride',
    'Baggio Husidic': 'Baggio Husidić',
    'Brian Haynes': 'Bryan Haynes',
    'Billy Baumhoff': 'Bill Baumhoff',
    'Benjamin Somoza': 'Ben Somoza',
    'Brendan (Blake) Camp': 'Blake Camp',
    'Christopher Schwarze': 'Chris Schwarze',
    'Christopher Gores': 'Chris Gores',
    'Chris Dore': 'Christopher Dore',
    'Christopher (Chris) Eylander': 'Chris Eylander',
    'Carlos Ruiz': 'Carlos Ruíz',
    'Cus Hiddink': 'Guus Hiddink',
    'Carlos Murriagui-Gonzalez': 'Andres Murriagui',
    'Craig (CJ) Klaas': 'C.J. Klaas',
    'CJ Sapong': 'C.J. Sapong',
    'Colin O’Donnell': 'Colin O\'Donnell',
    'Cuauhtemoc Blanco': 'Cuauhtémoc Blanco',
    'CJ Brown': 'C.J. Brown',
    'CJ Brown': 'C.J. Brown',
    'Cole Denormandie': 'Cole DeNormandie',
    'Camilo': 'Camilo Sanvezzo',
    'Colin Martin': 'Collin Martin',
    'Colin Mclocklan': 'Colin McLocklan',
    'Cristian Da Silva': 'Cristian da Silva',
    u'Claudio Su\xe1rez': 'Claudio Suarez',
    'Claudio Suarez': 'Claudio Suárez',
    u'Christian G\xf3mez': 'Christian Gomez',
    'Christian Gomez': 'Christian Gómez',
    'Chris Mcdonald': 'Chris McDonald',
    'Christopher Cortez': 'Chris Cortez',
    'Calros Hermosillo': 'Carlos Hermosillo',

    'Christoff Lindenmayer': 'Christof Lindenmayer',
    #[u'Ciaran O&#039;Brien', u'Dayton O&#039;Brien', u'John O&#039;Brien', u'Leighton O&#039;Brien', u'Ronnie O&#039;Brien']
    'Ciaran O\'brien': 'Ciaran O\'Brien',
    'Chris Rodrigues': 'Chris Rodriguez',
    'Christopher Rodriguez': 'Chris Rodriguez',
    'C. J. Sapong': 'C.J. Sapong',
    'Can Weaver': 'Cam Weaver',
    'Cedric Joqueviel': 'Cédric Joqueviel',
    'Carol-Ann Chenard': 'Carol-Ann Chénard',
    'Carol Anne Chenard': 'Carol-Ann Chénard',
    'Carol-Anne Chénard': 'Carol-Ann Chénard',
    'Dan Wasson': 'Daniel Wasson',
    'Douglas Lascody': 'Doug Lascody',
    'Digitil Takawira': 'Digital Takawira', 
    'Darly Powell': 'Darryl Powell', 
    'Daryl Powell': 'Darryl Powell', 
    'Dion Sebwe': 'Dionysus Sebwe',
    'Dillion Serna': 'Dillon Serna',
    'Damarcus Beasley': 'DaMarcus Beasley',
    u'Daniel Hern\xe1ndez': 'Daniel Hernandez',
    'DJ Countess': 'D.J. Countess',
    'Dedi Ben-Dayan': 'Dedi Ben Dayan',
    'David Diplacido': 'David DiPlacido',
    'Danny Devall': 'Danny DeVall',
    'Danilo Da Silva': 'Danilo da Silva',
    'David Demello': 'David DeMello',
    'Drew Mcathy': 'Drew McAthy',
    'David De La Torre': 'David de la Torre',
    u'Diego Guti\xe9rrez': 'Diego Gutierrez',
    'Diego Gutierrez': 'Diego Gutiérrez',
    u'Danny O\u2019Rourke': 'Danny O\'Rourke',
    'Danny O’Rourke': 'Danny O\'Rourke',
    'David Xausa': 'Davide Xausa',
    'Dragan Popovic': 'Dragan Popović',
    'Dwayne DeRosario': 'Dwayne De Rosario',
    'Dwayne de Rosario': 'Dwayne De Rosario',
    'Daniel (Dan) Kennedy': 'Dan Kennedy',
    'Daniel Kennedy': 'Dan Kennedy',
    'Duncan (Melvin) Tarley': 'Melvin Tarley',
    'Duncan Tarley': 'Melvin Tarley',
    'Danny ORourke': "Danny O'Rourke",
    'Daouda Kante': 'Daouda Kanté',
    'Desan Rusmir': 'Dejan Rusmir',
    'Dave Van den Bergh': 'Dave van den Bergh',
    'Daniel (Scott) Ikeda': 'Daniel Ikeda',
    'Daniel "Scott" Ikeda': 'Daniel Ikeda',
    'Demetrius White': 'DeMetrius White',
    'David Ditomasso': 'David DiTomasso',
    'Dennis Hamlett': 'Denis Hamlett',
    'Daniel Keat': 'Dan Keat',
    'Danny Califf': 'Dan Califf',
    'Daniel Cruz': 'Danny Cruz',

    'Eddie Johnson': 'Edward Johnson',
    'Emilo Renteria': 'Emilio Renteria',
    u'Emilio Renter\xeda': 'Emilio Renteria',
    'Eric (Ricky) Lewis': 'Ricky Lewis',
    'Ernie Stewart': 'Earnie Stewart',

    'Fred Degand': 'Fred DeGand',
    'Francisco Naves Cobo': 'Francisco Navas Cobo',
    'Francois (Didier) Menard': 'Francois Didier Menard',
    u'Fabi\xe1n Esp\xedndola': 'Fabian Espindola',
    'Francisco G\xf3mez': 'Francisco Gomez',
    'Francisco Gomez': 'Francisco Gómez',
    'Frederick (Ricky) Schramm': 'Ricky Schramm',
    'Frederico (Freddy) Juarez': 'Frederico Juarez',
    'Frank Sanfilipo': 'Frankie Sanfilippo',
    'Franky Van Der Elst': 'Franky van der Elst',
    'Fernando Ortiz-Solis': 'Fernando Ortiz Solis',

    'Garlon Cannon': 'G.R. Cannon',
    'Gerell Elliot': 'Gerell Elliott',
    'Guiseppe Galderisi': 'Giuseppe Galderisi',
    'Gabe Gervais': 'Gabriel Gervais',
    'Gerson Mayen': 'Gerson Mayén',
    'Geoffrey Cameron': 'Geoff Cameron',
    'Gregory Dalby': 'Greg Dalby',
    'George (Scott) Buete': 'Scott Buete',
    'George Buete': 'Scott Buete',
    'Giuseppe Depalo': 'Giuseppe DePalo',
    'Gary Depalma': 'Gary DePalma',
    'Giovanne Savarese': 'Giovanni Savarese',

    'Hicham Aaboubou': 'Hicham Aâboubou',
    u'Herculez G\xf3mez': 'Herculez Gomez',
    'Hong Myung Bo': 'Hong Myung-Bo',
    'Hercules Gomez': 'Herculez Gomez',
    'Hugo Perez': 'Hugo Pérez',
    'Hector Marchena': 'Héctor Marchena',
    'Hugo Sanchez': 'Hugo Sánchez',
    'Hector Ortiz': 'Héctor Ortíz',
    'Hong Myung-bo': 'Hong Myung-Bo',
    'Hristo Stoitchkov': 'Hristo Stoichkov',

    'Isaias Bardales': 'Isaias Bardales Jr.',
    'Isaias Bardales Jr': 'Isaias Bardales Jr.',
    'Ivan Mckinley': 'Ivan McKinley',

    'Jeff Scanella': 'Jeff Scannella',
    'John Kennedy Hurtado': 'Jhon Kennedy Hurtado',
    'Jimmy McLoughlin': 'Jimmy McLaughlin', 
    'Jamie Moreno': 'Jaime Moreno',
    'J. T. Murray': 'J.T. Murray',
    'JeVaughn Watson': 'Je-Vaughn Watson',
    'Javan Toure': 'Javan Torre',
    'Jeferson': 'Jéferson',
    'Juan Pablo Angel': 'Juan Pablo Ángel',
    'John Kowallik': 'John Kowalik',
    'Juergen Klinsmann': 'Jurgen Klinsmann',
    'John Kerr, Jr.': 'John Kerr Jr.',
    'Joe Addo': 'Joseph Addo',
    'Josmer Altidore': 'Jozy Altidore',
    'Joseph (Joey) Gjertsen': 'Joey Gjertsen',
    'Joseph Gjertsen': 'Joey Gjertsen',
    'James Alberts': 'Jay Alberts',
    'James (Jay) Alberts': 'Jay Alberts',
    'Jose (ZeRoberto) Gomes-Santana': 'Jose Gomes-Santana',
    'Jonathan (Jash) Lopuski': 'Jonathan Lopuski',
    'Joshua Hansen': 'Josh Hansen',
    'Joshua (Josh) Bolton': 'Joshua Bolton',
    'Jacob (Jake) Sagare': 'Jake Sagare',
    'John Menyongar': 'Johnny Menyongar',
    'Jason Hernandez': 'Jason Hernández',
    'Jamison Olave': 'Jámison Olave',
    'Joe- Max Moore': 'Joe-Max Moore',
    'Joe Max Moore': 'Joe-Max Moore',    'Joshua Tudela': 'Josh Tudela',
    'Jean Claude Desir': 'Jean-Claude Désir',
    'Jean-Claude Desir': 'Jean-Claude Désir',
    'Jesus Arellano': 'Jesús Arellano',
    'Josh Gros': 'Joshua Gros',
    'Jose Burciaga': 'Jose Burciaga Jr.',
    'Jacob Traeger': 'Jake Traeger',
    'John O Brien': 'John O\'Brien',
    'Joe Max Moore': 'Joe-Max Moore',
    'Jason Devos': 'Jason de Vos',
    'Jose Manuel Abundis': 'José Manuel Abundis',
    'Julio Cesar': 'Júlio César',
    'Jan Van Der Veen': 'Jan Van der Veen',
    'Jon Leathers': 'Jonathan Leathers',
    'Jan Van Bevern': 'Jan van Beveren',
    'Jan Van Beveren': 'Jan van Beveren',
    'Jean Phillippe Peguero': 'Jean Philippe Peguero',
    'Jurgen Sommer': 'Juergen Somme',
    'Juan Suarez': 'Juan Berthy Suarez',
    u'Juan Diego Gonz\xe1lez': 'Juan Diego Gonzalez',
    'Jim St Andre': 'Jim St. Andre',
    'JT Dorsey': 'J.T. Dorsey',
    'Jose Dasilva': 'Jose DaSilva',
    '\xa0Jose Cancela': 'Jose Cancela',
    'Joey Disalvo': 'Joey DiSalvo',
    'Joey Digiamarino': 'Joey DiGiamarino',
    'John Diraimondo': 'John DiRaimondo',
    'Jeff Devettori': 'Jeff DeVettori',
    'Jason Ditullio': 'Jason DiTullio',
    u'Juli\xe1n De Guzman': 'Julian De Guzman',
    u'Jos\xe9 Cancela': 'Jose Cancela',
    u'\xa0Jose Cancela': 'Jose Cancela',
    'Jose Burciaga Jr': 'Jose Burciaga Jr.',
    'Jonathan Mccurley': 'Jonathan McCurley',
    'JOHN Mccallion': 'John McCallion',
    'John Mccallion': 'John McCallion',
    'Justin S Hughes': 'Justin S. Hughes',
    'Jeff Dimaria': 'Jeff DiMaria',
    'Jerome Lee-Yaw': 'Jerome Lee Yaw',
    'James Dedeus': 'James DeDeus',
    'Jason Hern\xe1ndez': 'Jason Hernandez',
    u'J\xe1mison Olave': 'Jamison Olave',
    'JP Rodrigues': 'J.P. Rodrigues',
    'John Debrito': 'John DeBrito',
    'Joe Franchino': 'Joey Franchino',
    'Jasen Garey': 'Jason Garey',
    'Jean-Philippe Peguero': 'Jean Philippe Peguero',
    'Jeay Heaps': 'Jay Heaps',
    u'Jair Ben\xedtez': 'Jair Benitez',
    'Jose Torres': 'José Francisco Torres',

    'Keiran O\'brien': 'Keiran O\'Brien',
    'Kwame Watson Siriboe': 'Kwame Watson-Siriboe',
    'Kevin O\'brien': 'Kevin O\'Brien',
    'Kim Roentved': 'Kim Røntved',

    'Laurence Olum': 'Lawrence Olum',
    'Luis Landin': 'Luis Ángel Landín',
    'Luis Angel Landin': 'Luis Ángel Landín',
    'Luis Angel Land\xedn': 'Luis Ángel Landín',
    'Luis Angel Landín': 'Luis Ángel Landín',
    'Leighton O\'brien': 'Leighton O\'Brien',
    u'Leo Gonz\xe1lez': 'Leo Gonzalez',
    'Lee Young Jin': 'Lee Young-jin',
    'Lee Young-jin': 'Raúl Lara',
    'Leonel Alvarez': 'Leonel Álvarez',
    'Luis Fernando Zuleta-Mechura': 'Luis Zuleta-Mechura',
    'Louie (Lou) Rolko': 'Louie Rolko',
    'Leonid Krupnik': 'Leo Krupnik',
    'Leonid (Leo) Krupnik': 'Leo Krupnik',

    'Macoumba (Mac) Kandji': 'Macoumba Kandji',
    'Mike Ambersley': 'Michael Ambersley',
    'Michael (Mike) Ambersley': 'Michael Ambersley',
    'Manuel Lagos': 'Manny Lagos',
    'Mubarike (Mamba) Chisoni': 'Mubarike Chisoni',
    'Mauricio Salles-De Alencar': 'Mauricio Salles',
    'Matthew (Deli) Delicâte': 'Matthew Delicate',
    'Matthew Delic�te': 'Matthew Delicate',
    'Matthew (Matt) Bobo': 'Matt Bobo',
    'Michael Chabala': 'Mike Chabala',
    'Matthew Bobo': 'Matt Bobo',
    'Mike Zaher': 'Michael Zaher',
    'Mike Ambersley': 'Michael Ambersley',
    'Michael Fucito': 'Mike Fucito',
    'Momcilo Gavric': 'Momcilo Gavrić',
    u'Michael Uma\xf1a': 'Michael Umana',
    'Michael* Ueltschey': 'Michael Ueltschey',
    'MICHAEL Mcfarland': 'Michael McFarland',
    'Michael Mcfarland': 'Michael McFarland',
    'Mckinley Tennyson': 'McKinley Tennyson',
    'Michael Ambrose': 'Mike Ambrose',
    'Marco Delgado': 'Marky Delgado',
    'Marki Delgado': 'Marky Delgado',
    'Matt Gold': 'Matthew Gold',
    'Max Griffin': 'Maxwell Griffin',
    'Mario Ivan Guerrero': 'Ivan Guerrero',
    'Mike Lookingland': 'Michael Lookingland',
    'Mike Holody': 'Michael Holody',
    'Marros Paullo Peixoto': 'Marcos Paullo',
    'Marcos Peixoto': 'Marcos Paullo',
    'Mauricios Ramos': 'Mauricio Ramos', 
    'Marcos Saragosa': 'Marcelo Saragosa',
    'Michael Seamon': 'Mike Seamon',
    'Michael Slivinski': 'Mike Slivinski',
    'Mitchell Taintor': 'Mitch Taintor',
    'Michael Videira': 'Mike Videira',
    'Maxi Viera': 'Max Viera',
    'Marvin Ch\xe1vez': 'Marvin Chavez',
    'Marvin Chavez': 'Marvin Chávez',
    'Michael N\'doumbe': 'Michael N\'Doumbe',
    'Mike DuHaney': 'Mike Duhaney',
    u'Milton Rodr\xedguez': 'Milton Rodriguez',
    'Miguel Lopez': 'Miguel López',    
    'Miguel Montano': 'Miguel Montaño',
    'Martin Machon': 'Martín Machón',
    'Milos Kocic': 'Miloš Kočić',
    'Mikael Yourassawski': 'Mikael Yourassawsky',
    'Marco Paulos': 'Marcos Paullo',
    'Marcos Paulos': 'Marcos Paullo',
    'Marco Paullo Peioto': 'Marco Paullo',
    'Macoumba Kandi': 'Macoumba Kandji',

    'Nelson Gonzalez': 'Nelson González',
    'Nico Muniz': 'Nico Muñiz',
    'Nelson Gonz\xe1lez': 'Nelson Gonzalez',
    'Neil Mcnab': 'Neil McNab',
    'Nick Desantis': 'Nick De Santis',
    'Nick DeSantis': 'Nick De Santis',
    'Nathaniel (Nate) Winkel': 'Nate Winkel',
    'Nathaniel Winkel': 'Nate Winkel',
    'Nino Da Silva': 'Nino da Silva',
    'Nate Sturgis': 'Nathan Sturgis',

    'Omiz Namizi': 'Omid Namizi',
    'O\'neil Peart' :'O\'Neil Peart',
    'O’Brian White': 'O\'Brian White',
    u'O\u2019Brian White': 'O\'Brian White',
    'Orlando Perez': 'Orlando Pérez',
    'Orando Perez': 'Orlando Pérez',
    u'Orlando P\xe9rez': 'Orlando Perez',
    'Olukorede Aiyegbusi': 'Korede Aiyegbusi',
    'Oscar Pareja': 'Óscar Pareja',

    'Paulo Jr.': 'Paulo Araujo Jr.',
    'Paulo Junior': 'Paulo Araujo Jr.',
    'Paulo Araujo Jr': 'Paulo Araujo Jr.',
    'Paulo Da Silva': 'Paulo da Silva', # World Cup?
    'Petur Petursson': 'Pétur Petursson',
    'Peter Mcparland': 'Peter McParland',
    'Peri Marosevic': 'Perica Marošević',
    'Predrag Radosavljevic': 'Preki',
    'Pelé (Edson Arantes Do Nascimento)': 'Pelé',
    'Pele': 'Pelé',
    'Peter Baralic': 'Peter Baralić',
    'Paulinho': 'Paulinho McLaren',
    'Perry Van Der Beck': 'Perry Van der Beck',
    'Peter Van de Ven': 'Peter Van De Ven',
    'Petter Villegas-Espana': 'Petter Villegas',
    'Peter Villegas': 'Petter Villegas',
    'Paul O\'donnell': 'Paul O\'Donnell',
    u'Pablo Hern\xe1ndez': 'Pablo Hernandez',
    'Paul Decastro': 'Paul DeCastro',
    'Peter Lowry.': 'Peter Lowry',
    'Patrick Mcsorely': 'Patrick McSorely',
    'Pete Vagenas': 'Peter Vagenas',
    'Peter Sabanadzovic': 'Refik Sabanadzovic',
    'Peter Marino': 'Pete Marino',

    'Quincy Amirikwa': 'Quincy Amarikwa',
    'Quinn O\'sullivan': 'Quinn O\'Sullivan',
    'Ricardo (Kiki) Lara': 'Ricardo Lara',

    'Roland (Pato) Vargas-Aguilera': 'Roland Aguilera',
    'Roland (Pato) Aguilera': 'Roland Aguilera',
    'Roland Vargas-Aguilera': 'Roland Aguilera',
    'Rafael (Mime) Ortiz': 'Rafael Ortiz-Huertas',
    'Rodrigo Rios-Rodriguez': 'Rodrigo Rios',
    'Robert Valentino': 'Rob Valentino',
    'Robert Russell': 'Robbie Russell',
    'Rodrigo Lopez': 'Rodrigo López',
    'Raul Diaz Arce': 'Raúl Díaz Arce',
    'Ronnie O’Brien': 'Ronnie O\'Brien',
    'Ronald Cerritos': 'Rónald Cerritos',
    'Ross Mckenzie': 'Ross McKenzie',
    'Rauwshawn McKenzie': 'Rauwshan McKenzie',
    'Raivis Hščanovičs': 'Raivis Hscanovics',
    u'Ram\xf3n S\xe1nchez': 'Ramon Sanchez',
    'Robert Diguardi': 'Robert DiGuardi',
    'Remiro Corrales': 'Ramiro Corrales',
    'Raimo De Vries': 'Raimo de Vries',
    'Ruben Hernandez': 'Ruben Dario Hernandez',
    'Ryan De la Fuente': 'Bryan de la Fuente',
    'Rachid El Khalifi': 'Rachid el Khalifi',
    u'Rodrigo L\xf3pez': 'Rodrigo Lopez',
    u'Rafael M\xe1rquez': 'Rafael Marquez',
    'Robbie Aristidemo': 'Robbie Aristodemo',
    'Ross Labauex': 'Ross LaBeaux',
    'Ramon Nunez': 'Ramon Núñez',
    'RT Moore': 'R.T. Moore',
    'Ronnie O\'brien': 'Ronnie O\'Brien',
    u'Ronnie O\u2019Brien': 'Ronnie O\'Brien',
    'Ricky Balchan': 'Rich Balchan',
    'Ryseheim Henderson': 'Ryshiem Henderson', #http://en.wikipedia.org/wiki/Ryshiem_Henderson

    'Steven Vukovic': 'Stefan Vukovic',
    'Santiago Primm': 'Santiago Prim',
    'Stephen Wondolowski': 'Steve Wondolowski',
    'Steve Yallop': 'Frank Yallop',
    'Srdjan Djekanovic': 'Srdjan Djekanović',
    'Stefam Miglioranzi': 'Stefani Miglioranzi',
    u'St\xe9phane Auvray': 'Stephane Auvray',
    'Stephen DeRoux': 'Stephen deRoux',
    'Stuart Macrury': 'Stuart MacRury',
    'STUART Macrury': 'Stuart MacRury',
    'Sean Mcauley': 'Sean McAuley',
    u'S\xe9bastien Le Toux': 'Sebastien Le Toux',
    'Steve* Shak': 'Steve Shak',
    'Shawn Francis': 'Shaun Francis',
    'Stephen Wondolowski': 'Steve Wondolowski',
    'Stefani Dimitrov': 'Stefan Dimitrov',
    'Simon Elliot': 'Simon Elliott',
    'Stephen Herdsman': 'Steven Herdsmamn',
    'Steve Herdsman': 'Steven Herdsmamn',
    'Steven Keel': 'Stephen Keel',
    'Stephen Lenhart': 'Steven Lenhart',
    'Sebastien Le Toux': 'Sébastien Le Toux',
    'Shane Batelle': 'Shane Battelle',
    'Sandi Gbandi': 'Sandy Gbandi',
    'Sebastien Le Toux': 'Sébastien Le Toux',

    'Toni Stahl': 'Toni Ståhl',
    'Tino Nunez': 'Tino Nuñez',
    'Thomas (TJ) Tomasso': 'T.J. Tomasso',
    'Toni Stahl': 'Toni Ståhl',
    'Thabiso (Boyzzz) Khumalo': 'Thabiso Khumalo',
    'Thomas (Tom) Taylor': 'Tom Taylor',
    'Thomas Taylor': 'Tom Taylor',
    'Terence (Terry) Boss': 'Terry Boss',
    'Taiwo (Tai) Atieno': 'Taiwo Atieno',
    'Tomas Wygonik': 'Tomasz Wygonik',
    'Talifour Diane': 'Taifour Diané',
    'Tulio': 'Túlio',
    'Tosh Mckinlay': 'Tosh McKinlay',
    'Taifour Diane': 'Taifour Diané',
    'Thoams Dooley': 'Thomas Dooley',
    'Tom Dooley': 'Thomas Dooley',
    'Tenwya Bonseu': 'Tenywa Bonseu',
    'Tristen Bowen': 'Tristan Bowen',
    'Tommy Heinemann': 'Tom Heinemann',
    'Tom Heineman': 'Tom Heinemann',
    'Tyron Marshall': 'Tyrone Marshall', 
    'Tyronne Marshall': 'Tyrone Marshall', 
    'Thomas W. Cahill': 'Thomas Cahill',
    'Tiyiselani Shipalane': 'Tiyi Shipalane',

    'Uriel daVeiga': 'Uriel da Veiga',

    'Valdemar Teixeira-Gomes': 'Valdemar Teixeira',
    'Vojislav "Scoop" Stanisic': 'Scoop Stanisic',
    'Victor Estupiñan': 'Víctor Estupiñán',
    'Victor Estupinan': 'Víctor Estupiñán',
    'Victor Estupiñán': 'Víctor Estupiñán',
    'Vitalis Takawira': 'Digital Takawira', 

    'Williams Sunsing': 'William Sunsing',
    'Welton': 'Welton Melo',
    'William (Cam) Weaver': 'Cam Weaver',
    'Wolfgang Sunholz': 'Wolfgang Suhnholz', 
    'Winston Dubose': 'Winston DuBose',
    'William Hesmer': 'Will Hesmer',
    'Welton': 'Welton Melo',

    'Young Jueng Cho': 'Cho Young-Jeung',
    'Young Jeung Cho': 'Cho Young-Jeung',

    'Zach Schilawski': 'Zack Schilawski',
    'Zacharias (Zach) Scott': 'Zach Scott',
    'Zachary Herold': 'Zac Herold',
    'Zach Kingsley': 'Zack Kingsley',
    'Zanzan': 'Zanzan Atte-Oudeyi',    
}


def get_name(name, league=None):
    name = name.strip()
    if league and (name, league) in names:
        name = names[(name, league)]
        return get_name(name, league)

    if name in names:
        nname = get_name(names[name])
        if nname in names:
            print nname
        return nname
    return name
