#!/usr/local/bin/env python
# -*- coding: utf-8 -*-


names = {


    # ASL 1933-1984
    'Quinones': 'Enrique Quinones',

    'John Kowallik': 'John Kowalik',
    'Young Jueng Cho': 'Cho Young-Jeung',
    'Young Jeung Cho': 'Cho Young-Jeung',
    'Wolfgang Sunholz': 'Wolfgang Suhnholz', 
    'Dragan Popovic': 'Dragan Popović',
    'Uriel daVeiga': 'Uriel da Veiga',

    
    'Cus Hiddink': 'Guus Hiddink',
    'Vojislav "Scoop" Stanisic': 'Scoop Stanisic',
    'Thomas (TJ) Tomasso': 'T.J. Tomasso',
    'Juergen Klinsmann': 'Jurgen Klinsmann',
    'Frederick (Ricky) Schramm': 'Ricky Schramm',
    'Valdemar Teixeira-Gomes': 'Valdemar Teixeira',
    'Michael Chabala': 'Mike Chabala',
    'Robert Valentino': 'Rob Valentino',
    'Carlos Murriagui-Gonzalez': 'Andres Murriagui',
    'David Xausa': 'Davide Xausa',
    'Ali-John Utush': 'Ali John Utush',
    'Alijohn Utush': 'Ali John Utush',
    'Dwayne DeRosario': 'Dwayne De Rosario',
    'Hristo Stoitchkov': 'Hristo Stoichkov',
    'Robert Russell': 'Robbie Russell',
    'Winston Dubose': 'Winston DuBose',
    'Alvaro Saborio': 'Álvaro Saborío',
    'Toni Stahl': 'Toni Ståhl',
    'Andre Sherard': 'André Sherard',
    'John Kerr, Jr.': 'John Kerr Jr.',
    'Zach Schilawski': 'Zack Schilawski',
    'Shane Batelle': 'Shane Battelle',
    'Joe Addo': 'Joseph Addo',
    'George (Scott) Buete': 'Scott Buete',
    'George Buete': 'Scott Buete',
    'Daniel (Dan) Kennedy': 'Dan Kennedy',
    'Daniel Kennedy': 'Dan Kennedy',
    'William (Cam) Weaver': 'Cam Weaver',
    'Duncan (Melvin) Tarley': 'Melvin Tarley',
    'Duncan Tarley': 'Melvin Tarley',
    'Alexis (Pasa) Rivera': 'Alexis Rivera',
    'Frederico (Freddy) Juarez': 'Frederico Juarez',
    'Ricardo (Kiki) Lara': 'Ricardo Lara',
    'Zacharias (Zach) Scott': 'Zach Scott',
    'Nathaniel (Nate) Winkel': 'Nate Winkel',
    'Nathaniel Winkel': 'Nate Winkel',
    'Terence (Terry) Boss': 'Terry Boss',
    'Joseph (Joey) Gjertsen': 'Joey Gjertsen',
    'Joseph Gjertsen': 'Joey Gjertsen',
    'Matthew (Deli) Delicâte': 'Matthew Delicate',
    'Matthew Delic�te': 'Matthew Delicate',
    'Eric (Ricky) Lewis': 'Ricky Lewis',
    'Brendan (Blake) Camp': 'Blake Camp',
    'Matthew (Matt) Bobo': 'Matt Bobo',
    'Matthew Bobo': 'Matt Bobo',
    'Alexis Rivera-Curet': 'Alexis Rivera',
    'James Alberts': 'Jay Alberts',
    'James (Jay) Alberts': 'Jay Alberts',
    'Taiwo (Tai) Atieno': 'Taiwo Atieno',
    'Jose (ZeRoberto) Gomes-Santana': 'Jose Gomes-Santana',
    'Mauricio Salles-De Alencar': 'Mauricio Salles',
    'Welton': 'Welton Melo',
    'Roland (Pato) Aguilera': 'Roland Aguilera',
    'Roland Vargas-Aguilera': 'Roland Aguilera',
    'Anthony McManus': 'Tony McManus',
    'Anthony (Tony) McManus': 'Tony McManus',
    'Christopher Schwarze': 'Chris Schwarze',
    'Tomas Wygonik': 'Tomasz Wygonik',
    'Roland (Pato) Vargas-Aguilera': 'Roland Aguilera',
    'Chris Dore': 'Christopher Dore',
    'Sandi Gbandi': 'Sandy Gbandi',
    'Luis Fernando Zuleta-Mechura': 'Luis Zuleta-Mechura',
    'Petter Villegas-Espana': 'Petter Villegas',
    'Peter Villegas': 'Petter Villegas',
    'Alberto (Cuba) Delgado': 'Alberto Delgado',
    'Christopher Gores': 'Chris Gores',
    'Rafael (Mime) Ortiz': 'Rafael Ortiz-Huertas',
    'Jonathan (Jash) Lopuski': 'Jonathan Lopuski',
    'Joshua Hansen': 'Josh Hansen',
    'Louie (Lou) Rolko': 'Louie Rolko',
    'Thabiso (Boyzzz) Khumalo': 'Thabiso Khumalo',
    'Leonid Krupnik': 'Leo Krupnik',
    'Leonid (Leo) Krupnik': 'Leo Krupnik',
    'Rodrigo Rios-Rodriguez': 'Rodrigo Rios',
    'Joshua (Josh) Bolton': 'Joshua Bolton',
    'Macoumba (Mac) Kandji': 'Macoumba Kandji',
    'Mike Ambersley': 'Michael Ambersley',
    'Michael (Mike) Ambersley': 'Michael Ambersley',
    'Benjamin Somoza': 'Ben Somoza',
    'Mubarike (Mamba) Chisoni': 'Mubarike Chisoni',
    'Thomas (Tom) Taylor': 'Tom Taylor',
    'Thomas Taylor': 'Tom Taylor',
    'Christopher (Chris) Eylander': 'Chris Eylander',
    'Jacob (Jake) Sagare': 'Jake Sagare',
    'John Menyongar': 'Johnny Menyongar',
    'Alan Mcloughlin': 'Alan McLoughlin',
    'Rodrigo Lopez': 'Rodrigo López',
    'Anthony De Avila': 'Anthony de Avila',
    'Orlando Perez': 'Orlando Pérez',
    'Orando Perez': 'Orlando Pérez',
    'Raul Diaz Arce': 'Raúl Díaz Arce',
    'Ronnie O’Brien': 'Ronnie O\'Brien',
    'CJ Sapong': 'C.J. Sapong',
    'Adrian Paz': 'Adrián Paz',
    'Jason Hernandez': 'Jason Hernández',
    'Jamison Olave': 'Jámison Olave',
    'Ronald Cerritos': 'Rónald Cerritos',
    'Leonel Alvarez': 'Leonel Álvarez',
    'Toni Stahl': 'Toni Ståhl',
    'Hugo Perez': 'Hugo Pérez',
    'Danny O’Rourke': 'Danny O\'Rourke',
    'Ross Mckenzie': 'Ross McKenzie',
    'Sebastien Le Toux': 'Sébastien Le Toux',
    'Cuauhtemoc Blanco': 'Cuauhtémoc Blanco',
    'Joe- Max Moore': 'Joe-Max Moore',
    'Joe Max Moore': 'Joe-Max Moore',
    'CJ Brown': 'C.J. Brown',
    'Joshua Tudela': 'Josh Tudela',
    'Billy Baumhoff': 'Bill Baumhoff',
    'Frank Sanfilipo': 'Frankie Sanfilippo',
    'Andrew Rosenband': 'Andy Rosenband',
    'Jacob Traeger': 'Jake Traeger',
    'William Hesmer': 'Will Hesmer',
    'Antouman Jallow': 'Antou Jallow',
    

    

    # World Cup?
    'Paulo Da Silva': 'Paulo da Silva',
    'Tulio': 'Túlio',
    'Hector Marchena': 'Héctor Marchena',
    'Petur Petursson': 'Pétur Petursson',
    'Franky Van Der Elst': 'Franky van der Elst',
    'Lee Young Jin': 'Lee Young-jin',
    'Lee Young-jin': 'Raúl Lara',
    'Colin O’Donnell': 'Colin O\'Donnell',
    'Hugo Sanchez': 'Hugo Sánchez',
    'Jean Claude Desir': 'Jean-Claude Désir',
    'Jean-Claude Desir': 'Jean-Claude Désir',
    'Jesus Arellano': 'Jesús Arellano',
    'Hector Ortiz': 'Héctor Ortíz',
    'Tosh Mckinlay': 'Tosh McKinlay',
    'Peter Mcparland': 'Peter McParland',
    'Hong Myung-bo': 'Hong Myung-Bo',
    'Oscar Pareja': 'Óscar Pareja',
    

    

    

    # MLS Drafts
    'Mike Zaher': 'Michael Zaher',
    'Peri Marosevic': 'Perica Marošević',
    'A. J. DeLaGarza': 'A.J. DeLaGarza',
    'Mike Ambersley': 'Michael Ambersley',
    'Josh Gros': 'Joshua Gros',
    'Craig (CJ) Klaas': 'C.J. Klaas',
    'Ernie Stewart': 'Earnie Stewart',
    'Michael Fucito': 'Mike Fucito',
    'Jose Burciaga': 'Jose Burciaga Jr.',
    'Isaias Bardales': 'Isaias Bardales Jr.',
    'Predrag Radosavljevic': 'Preki',
    'Brian Haynes': 'Bryan Haynes',
    'Geoffrey Cameron': 'Geoff Cameron',
    'Akeem Priestly': 'Akeem Priestley',
    'Gregory Dalby': 'Greg Dalby',

    

    # World Cup
    'Pelé (Edson Arantes Do Nascimento)': 'Pelé',
    'Pele': 'Pelé',
    'John O Brien': 'John O\'Brien',
    'Joe Max Moore': 'Joe-Max Moore',
    


    # Nasl?
    'Momcilo Gavric': 'Momcilo Gavrić',
    'Jan Van Der Veen': 'Jan Van der Veen',
    'Antonio De La Torre': 'Antonio de la Torre',
    'Peter Baralic': 'Peter Baralić',



    # US Minor leagues
    'Talifour Diane': 'Taifour Diané',
    'Jason Devos': 'Jason de Vos',
    'Robbie Aristidemo': 'Robbie Aristodemo',
    'Gabe Gervais': 'Gabriel Gervais',

    'Paulinho': 'Paulinho McLaren',
    'Danny ORourke': "Danny O'Rourke",
    'CJ Brown': 'C.J. Brown',
    'Ross Labauex': 'Ross LaBeaux',
    'Perry Van Der Beck': 'Perry Van der Beck',
    'Gerson Mayen': 'Gerson Mayén',
    'Nelson Gonzalez': 'Nelson González',
    'Jose Manuel Abundis': 'José Manuel Abundis',
    'Daouda Kante': 'Daouda Kanté',
    'AJ Jeffries': 'A.J. Jeffries',
    'Fernando Ortiz-Solis': 'Fernando Ortiz Solis',
    'Alex Pineda Chacon': 'Alex Pineda Chacón',
    'Julio Cesar': 'Júlio César',
    'Abé Matamoros': 'Ábe Matamoros',
    'Abe Matamoros': 'Ábe Matamoros',
    'Miguel Lopez': 'Miguel López',
    'Ramon Nunez': 'Ramon Núñez',
    
    'Miguel Montano': 'Miguel Montaño',
    'Martin Machon': 'Martín Machón',
    'Sebastien Le Toux': 'Sébastien Le Toux',
    'Jeferson': 'Jéferson',
    'Baggio Husidic': 'Baggio Husidić',
    'Milos Kocic': 'Miloš Kočić',
    'Nico Muniz': 'Nico Muñiz',
    'Cole Denormandie': 'Cole DeNormandie',
    'Tino Nunez': 'Tino Nuñez',
    'Juan Pablo Angel': 'Juan Pablo Ángel',
    

    


    'Camilo': 'Camilo Sanvezzo',
    'Mikael Yourassawski': 'Mikael Yourassawsky',
    'Steven Vukovic': 'Stefan Vukovic',
    'Santiago Primm': 'Santiago Prim',
    'JeVaughn Watson': 'Je-Vaughn Watson',
    'Marco Paulos': 'Marcos Paullo',
    'Marcos Paulos': 'Marcos Paullo',
    'Marco Paullo Peioto': 'Marco Paullo',
    'Paulo Jr.': 'Paulo Araujo Jr.',
    'Paulo Junior': 'Paulo Araujo Jr.',
    'Paulo Araujo Jr': 'Paulo Araujo Jr.',
    'Andi Iro': 'Andy Iro',
    'Javan Toure': 'Javan Torre',
    'Colin Martin': 'Collin Martin',
    'Desan Rusmir': 'Dejan Rusmir',
    'Ricky Balchan': 'Rich Balchan',
    'Andy Gruenenbaum': 'Andy Gruenebaum',
    'Quincy Amirikwa': 'Quincy Amarikwa',
    'Macoumba Kandi': 'Macoumba Kandji',

    'Victor Estupiñan': 'Víctor Estupiñán',
    'Victor Estupinan': 'Víctor Estupiñán',
    'Victor Estupiñán': 'Víctor Estupiñán',
    
    'Olukorede Aiyegbusi': 'Korede Aiyegbusi',
    
    'Ryseheim Henderson': 'Ryshiem Henderson', #http://en.wikipedia.org/wiki/Ryshiem_Henderson
    'Welton': 'Welton Melo',
    'Hercules Gomez': 'Herculez Gomez',
    'RT Moore': 'R.T. Moore',
    'Brian Mcbride': 'Brian McBride',
    'Austin Da Luz': 'Austin da Luz',
    'Ronnie O\'brien': 'Ronnie O\'Brien',
    u'Ronnie O\u2019Brien': 'Ronnie O\'Brien',
    'Keiran O\'brien': 'Keiran O\'Brien',
    'Neil Mcnab': 'Neil McNab',
    'Jason Hern\xe1ndez': 'Jason Hernandez',
    u'J\xe1mison Olave': 'Jamison Olave',
    u'Abraham Fran\xe7ois': 'Abraham Francois',
    'Giuseppe Depalo': 'Giuseppe DePalo',
    'James Dedeus': 'James DeDeus',
    'JP Rodrigues': 'J.P. Rodrigues',
    u'Leo Gonz\xe1lez': 'Leo Gonzalez',
    'John Debrito': 'John DeBrito',
    'Nick Desantis': 'Nick De Santis',
    'Nick DeSantis': 'Nick De Santis',
    'AJ Wood': 'A.J. Wood',
    u'Orlando P\xe9rez': 'Orlando Perez',
    u'Jair Ben\xedtez': 'Jair Benitez',
    'Dave Van den Bergh': 'Dave van den Bergh',
    u'Michael Uma\xf1a': 'Michael Umana',
    u'Rodrigo L\xf3pez': 'Rodrigo Lopez',
    'Daniel (Scott) Ikeda': 'Daniel Ikeda',
    'Daniel "Scott" Ikeda': 'Daniel Ikeda',
    u'St\xe9phane Auvray': 'Stephane Auvray',
    'Demetrius White': 'DeMetrius White',
    'Francisco G\xf3mez': 'Francisco Gomez',
    'Stephen DeRoux': 'Stephen deRoux',
    'Stuart Macrury': 'Stuart MacRury',
    'STUART Macrury': 'Stuart MacRury',
    'Jeff Dimaria': 'Jeff DiMaria',
    'Brandon Mcdonald': 'Brandon McDonald',
    'Peter Van de Ven': 'Peter Van De Ven',
    'Nelson Gonz\xe1lez': 'Nelson Gonzalez',
    'Damarcus Beasley': 'DaMarcus Beasley',
    u'Rafael M\xe1rquez': 'Rafael Marquez',
    'Brett Mcdermott': 'Brett McDermott',
    'Sean Mcauley': 'Sean McAuley',
    'Cristian Da Silva': 'Cristian da Silva',
    'ANDREW Mcdermott': 'Andrew McDermott',
    'Andrew Mcdermott': 'Andrew McDermott',
    'Leighton O\'brien': 'Leighton O\'Brien',
    u'\xc1lvaro Fern\xe1ndez': 'Alvaro Fernandez',
    'Jerome Lee-Yaw': 'Jerome Lee Yaw',
    'Michael* Ueltschey': 'Michael Ueltschey',
    'Danny Devall': 'Danny DeVall',
    'Danilo Da Silva': 'Danilo da Silva',
    'JT Dorsey': 'J.T. Dorsey',
    u'Andr\xe9s Mendoza': 'Andres Mendoza',
    'David Demello': 'David DeMello',
    'Jose Dasilva': 'Jose DaSilva',
    u'Herculez G\xf3mez': 'Herculez Gomez',
    u'Pablo Hern\xe1ndez': 'Pablo Hernandez',
    'Drew Mcathy': 'Drew McAthy',
    'Marvin Ch\xe1vez': 'Marvin Chavez',
    'Quinn O\'sullivan': 'Quinn O\'Sullivan',
    u'Alvaro Sabor\xedo': 'Alvaro Saborio',
    u'\xc1lvaro Sabor\xedo': 'Alvaro Saborio',
    'David De La Torre': 'David de la Torre',
    'Paul Decastro': 'Paul DeCastro',
    u'Claudio Su\xe1rez': 'Claudio Suarez',
    u'Emilio Renter\xeda': 'Emilio Renteria',
    u'Diego Guti\xe9rrez': 'Diego Gutierrez',
    u'Danny O\u2019Rourke': 'Danny O\'Rourke',
    'Joey Disalvo': 'Joey DiSalvo',
    'Joey Digiamarino': 'Joey DiGiamarino',
    'John Diraimondo': 'John DiRaimondo',
    'DJ Countess': 'D.J. Countess',
    'Alex Pineda-Chacon': 'Alex Pineda Chacon',
    'Justin S Hughes': 'Justin S. Hughes',
    'Michael N\'doumbe': 'Michael N\'Doumbe',
    'Jeff Devettori': 'Jeff DeVettori',
    'Jason Ditullio': 'Jason DiTullio',
    u'Juli\xe1n De Guzman': 'Julian De Guzman',
    'Mike DuHaney': 'Mike Duhaney',
    'Dedi Ben-Dayan': 'Dedi Ben Dayan',
    'David Diplacido': 'David DiPlacido',
    u'Jos\xe9 Cancela': 'Jose Cancela',
    u'\xa0Jose Cancela': 'Jose Cancela',
    u'Fabi\xe1n Esp\xedndola': 'Fabian Espindola',
    'Kevin O\'brien': 'Kevin O\'Brien',
    'Isaias Bardales Jr': 'Isaias Bardales Jr.',
    'Nino Da Silva': 'Nino da Silva',
    'Antonio De Avila': 'Antonio de Avila',
    'Jose Burciaga Jr': 'Jose Burciaga Jr.',
    u'Christian G\xf3mez': 'Christian Gomez',
    'Paul O\'donnell': 'Paul O\'Donnell',
    'Gary Depalma': 'Gary DePalma',
    u'S\xe9bastien Le Toux': 'Sebastien Le Toux',
    'Rachid El Khalifi': 'Rachid el Khalifi',
    'Jonathan Mccurley': 'Jonathan McCurley',
    'Brad Mcglaughlin': 'Brad McGlaughlin',
    u'Daniel Hern\xe1ndez': 'Daniel Hernandez',
    u'Milton Rodr\xedguez': 'Milton Rodriguez',
    'JOHN Mccallion': 'John McCallion',
    'John Mccallion': 'John McCallion',
    'Andy Mcmahon': 'Andy McMahon',
    'Francois (Didier) Menard': 'Francois Didier Menard',
    'Anthony Mckeon': 'Anthony McKeon',
    u'O\u2019Brian White': 'O\'Brian White',
    u'Andr\xe9 Luiz': 'Andre Luiz',
    'Kwame Watson Siriboe': 'Kwame Watson-Siriboe',
    'Ivan Mckinley': 'Ivan McKinley',
    'Jim St Andre': 'Jim St. Andre',
    'Hong Myung Bo': 'Hong Myung-Bo',
    u'Juan Diego Gonz\xe1lez': 'Juan Diego Gonzalez',
    u'Ram\xf3n S\xe1nchez': 'Ramon Sanchez',
    'Patrick Mcsorely': 'Patrick McSorely',
    'Steve* Shak': 'Steve Shak',
    'Robert Diguardi': 'Robert DiGuardi',
    'Fred Degand': 'Fred DeGand',
    'CJ Brown': 'C.J. Brown',
    'AJ DeLaGarza': 'A.J. DeLaGarza',
    'Luis Angel Land\xedn': 'Luis Angel Landin',
    u'\xc1lvaro S\xe1nchez': 'Alvaro Sanchez',
    'David Ditomasso': 'David DiTomasso',
    'O\'neil Peart' :'O\'Neil Peart',
    'MICHAEL Mcfarland': 'Michael McFarland',
    'Michael Mcfarland': 'Michael McFarland',
    'Mckinley Tennyson': 'McKinley Tennyson',
    'Peter Lowry.': 'Peter Lowry',
    'Jean-Philippe Peguero': 'Jean Philippe Peguero',
    'Raimo De Vries': 'Raimo de Vries',
    'Chris Mcdonald': 'Chris McDonald',
    'Stephen Wondolowski': 'Steve Wondolowski',
    'Michael Ambrose': 'Mike Ambrose',
    'Bill Andracki': 'Billy Andracki',
    'Tenwya Bonseu': 'Tenywa Bonseu',
    'Tristen Bowen': 'Tristan Bowen',
    'Danny Califf': 'Dan Califf',
    'Garlon Cannon': 'G.R. Cannon',
    'Bryan Carroll': 'Brian Carroll',
    'Albert Celades': 'Alberto Celades',
    'Francisco Naves Cobo': 'Francisco Navas Cobo',
    'Remiro Corrales': 'Ramiro Corrales',
    'Christopher Cortez': 'Chris Cortez',
    'Daniel Cruz': 'Danny Cruz',
    'Marco Delgado': 'Marky Delgado',
    'Marki Delgado': 'Marky Delgado',
    'Stefani Dimitrov': 'Stefan Dimitrov',
    'Thoams Dooley': 'Thomas Dooley',
    'Tom Dooley': 'Thomas Dooley',
    'Simon Elliot': 'Simon Elliott',
    'Gerell Elliot': 'Gerell Elliott',
    'Joe Franchino': 'Joey Franchino',
    'Shawn Francis': 'Shaun Francis',
    'Ryan De la Fuente': 'Bryan de la Fuente',
    'Guiseppe Galderisi': 'Giuseppe Galderisi',
    'Jasen Garey': 'Jason Garey',
    'Blair Gaven': 'Blair Gavin',
    'A. J. Godbolt': 'A.J. Godbolt',
    'Matt Gold': 'Matthew Gold',
    'Max Griffin': 'Maxwell Griffin',
    'Mario Ivan Guerrero': 'Ivan Guerrero',
    'Andrew Hainault': 'André Hainault',
    'Andre Hainault': 'André Hainault',
    'Dennis Hamlett': 'Denis Hamlett',
    'Jeay Heaps': 'Jay Heaps',
    'Tommy Heinemann': 'Tom Heinemann',
    'Tom Heineman': 'Tom Heinemann',
    'Stephen Herdsman': 'Steven Herdsmamn',
    'Steve Herdsman': 'Steven Herdsmamn',
    'Calros Hermosillo': 'Carlos Hermosillo',
    'Ruben Hernandez': 'Ruben Dario Hernandez',
    'Zachary Herold': 'Zac Herold',
    'Mike Holody': 'Michael Holody',
    'John Kennedy Hurtado': 'Jhon Kennedy Hurtado',
    'Daniel Keat': 'Dan Keat',
    'Steven Keel': 'Stephen Keel',
    'Zach Kingsley': 'Zack Kingsley',
    'Luis Landin': 'Luis Angel Landin',
    'Douglas Lascody': 'Doug Lascody',
    'Stephen Lenhart': 'Steven Lenhart',
    'Christoff Lindenmayer': 'Christof Lindenmayer',
    'Mike Lookingland': 'Michael Lookingland',
    'Peter Marino': 'Pete Marino',
    'Tyron Marshall': 'Tyrone Marshall', 
    'Tyronne Marshall': 'Tyrone Marshall', 
    'Rauwshawn McKenzie': 'Rauwshan McKenzie',
    'Jimmy McLoughlin': 'Jimmy McLaughlin', 
    'Stefam Miglioranzi': 'Stefani Miglioranzi',
    'Jamie Moreno': 'Jaime Moreno',
    'Alex Morfaw': 'Alexandre Morfaw',
    'Albert Munoz': 'Alberto Munoz',
    'J. T. Murray': 'J.T. Murray',
    'Brian Namoff': 'Bryan Namoff',
    'Byran Namoff': 'Bryan Namoff',
    'Omiz Namizi': 'Omid Namizi',
    #[u'Ciaran O&#039;Brien', u'Dayton O&#039;Brien', u'John O&#039;Brien', u'Leighton O&#039;Brien', u'Ronnie O&#039;Brien']
    'Laurence Olum': 'Lawrence Olum',
    'Jean Phillippe Peguero': 'Jean Philippe Peguero',
    'Marros Paullo Peixoto': 'Marcos Paullo',
    'Marcos Peixoto': 'Marcos Paullo',
    'Darly Powell': 'Darryl Powell', 
    'Daryl Powell': 'Darryl Powell', 
    'Alex Prampin': 'Alan Prampin',
    'Mauricios Ramos': 'Mauricio Ramos', 
    'Emilo Renteria': 'Emilio Renteria',
    'Chris Rodrigues': 'Chris Rodriguez',
    'Christopher Rodriguez': 'Chris Rodriguez',
    'Peter Sabanadzovic': 'Refik Sabanadzovic',
    'C. J. Sapong': 'C.J. Sapong',
    'Marcos Saragosa': 'Marcelo Saragosa',
    'Giovanne Savarese': 'Giovanni Savarese',
    'Michael Seamon': 'Mike Seamon',
    'Dion Sebwe': 'Dionysus Sebwe',
    'Dillion Serna': 'Dillon Serna',
    'Tiyiselani Shipalane': 'Tiyi Shipalane',
    'Michael Slivinski': 'Mike Slivinski',
    'A. J. Soares': 'A.J. Soares',
    'Jurgen Sommer': 'Juergen Somme',
    'Nate Sturgis': 'Nathan Sturgis',
    'Juan Suarez': 'Juan Berthy Suarez',
    'Williams Sunsing': 'William Sunsing',
    'Mitchell Taintor': 'Mitch Taintor',
    'Digitil Takawira': 'Digital Takawira', 
    'Vitalis Takawira': 'Digital Takawira', 
    'Pete Vagenas': 'Peter Vagenas',
    'Michael Videira': 'Mike Videira',
    'Maxi Viera': 'Max Viera',
    'Bujon Vuckovic': 'Bojan Vuckovic',
    'Bo Vuckovic': 'Bojan Vuckovic',
    'Dan Wasson': 'Daniel Wasson',
    'Can Weaver': 'Cam Weaver',
    'Andrew Webber': 'Andrew Weber',
    'Stephen Wondolowski': 'Steve Wondolowski',

    'Steve Yallop': 'Frank Yallop',
    

    # Canadian Championship
    'Zanzan': 'Zanzan Atte-Oudeyi',    
    'Srdjan Djekanovic': 'Srdjan Djekanović',
    'Raivis Hščanovičs': 'Raivis Hscanovics',
    'Cedric Joqueviel': 'Cédric Joqueviel',
    'Hicham Aaboubou': 'Hicham Aâboubou',
    'Jon Leathers': 'Jonathan Leathers',


    # Whatever?
    'Jan Van Bevern': 'Jan van Beveren',
    'Jan Van Beveren': 'Jan van Beveren',
    'Thomas W. Cahill': 'Thomas Cahill',
    'Bora Milutinovic': 'Bora Milutinović',
    'Kim Roentved': 'Kim Røntved',

    # Refs
    'Carol-Ann Chenard': 'Carol-Ann Chénard',
    'Carol Anne Chenard': 'Carol-Ann Chénard',
    'Carol-Anne Chénard': 'Carol-Ann Chénard',


}


def get_name(name, league=None):
    name = name.strip()
    if league and (name, league) in names:
        name = names[(name, league)]
        return get_name(name, league)

    if name in names:
        nname = get_name(names[name])
        if nname in names:
            print nname
        return nname
    return name
