#!/usr/local/bin/env python
# -*- coding: utf-8 -*-


names = {

    # World Cup
    'Pelé (Edson Arantes Do Nascimento)': 'Pelé',
    'Pele': 'Pelé',
    


    # Nasl?
    'Momcilo Gavric': 'Momcilo Gavrić',
    'Jan Van Der Veen': 'Jan Van der Veen',
    'Antonio De La Torre': 'Antonio de la Torre',
    'Peter Baralic': 'Peter Baralić',



    # US Minor leagues
    'Talifour Diane': 'Taifour Diané',
    'Jason Devos': 'Jason de Vos',
    'Robbie Aristidemo': 'Robbie Aristodemo',
    'Gabe Gervais': 'Gabriel Gervais',

    'Paulinho': 'Paulinho McLaren',
    'Danny ORourke': "Danny O'Rourke",
    'CJ Brown': 'C.J. Brown',
    'Ross Labauex': 'Ross LaBeaux',
    'Perry Van Der Beck': 'Perry Van der Beck',
    'Gerson Mayen': 'Gerson Mayén',
    'Nelson Gonzalez': 'Nelson González',
    'Jose Manuel Abundis': 'José Manuel Abundis',
    'Daouda Kante': 'Daouda Kanté',
    'AJ Jeffries': 'A.J. Jeffries',
    'Fernando Ortiz-Solis': 'Fernando Ortiz Solis',
    'Alex Pineda Chacon': 'Alex Pineda Chacón',
    'Julio Cesar': 'Júlio César',
    'Abé Matamoros': 'Ábe Matamoros',
    'Abe Matamoros': 'Ábe Matamoros',
    'Miguel Lopez': 'Miguel López',
    'Ramon Nunez': 'Ramon Nuñez',
    'Miguel Montano': 'Miguel Montaño',
    'Martin Machon': 'Martín Machón',
    'Sebastien Le Toux': 'Sébastien Le Toux',
    'Jeferson': 'Jéferson',
    'Baggio Husidic': 'Baggio Husidić',
    'Milos Kocic': 'Miloš Kočić',
    'Nico Muniz': 'Nico Muñiz',
    'Cole Denormandie': 'Cole DeNormandie',
    'Tino Nunez': 'Tino Nuñez',
    'Juan Pablo Angel': 'Juan Pablo Ángel',
    

    


    'Camilo': 'Camilo Sanvezzo',
    'Mikael Yourassawski': 'Mikael Yourassawsky',
    'Steven Vukovic': 'Stefan Vukovic',
    'Santiago Primm': 'Santiago Prim',
    'JeVaughn Watson': 'Je-Vaughn Watson',
    'Marco Paulos': 'Marcos Paullo',
    'Marcos Paulos': 'Marcos Paullo',
    'Marco Paullo Peioto': 'Marco Paullo',
    'Paulo Jr.': 'Paulo Araujo Jr.',
    'Paulo Junior': 'Paulo Araujo Jr.',
    'Paulo Araujo Jr': 'Paulo Araujo Jr.',
    'Andi Iro': 'Andy Iro',
    'Javan Toure': 'Javan Torre',
    'Colin Martin': 'Collin Martin',
    'Desan Rusmir': 'Dejan Rusmir',
    'Ricky Balchan': 'Rich Balchan',
    'Andy Gruenenbaum': 'Andy Gruenebaum',
    'Quincy Amirikwa': 'Quincy Amarikwa',
    'Macoumba Kandi': 'Macoumba Kandji',

    'Victor Estupiñan': 'Víctor Estupiñán',
    'Victor Estupinan': 'Víctor Estupiñán',
    'Victor Estupiñán': 'Víctor Estupiñán',
    
    'Olukorede Aiyegbusi': 'Korede Aiyegbusi',
    
    'Ryseheim Henderson': 'Ryshiem Henderson', #http://en.wikipedia.org/wiki/Ryshiem_Henderson
    'Welton': 'Welton Melo',
    'Hercules Gomez': 'Herculez Gomez',
    'RT Moore': 'R.T. Moore',
    'Brian Mcbride': 'Brian McBride',
    'Austin Da Luz': 'Austin da Luz',
    'Ronnie O\'brien': 'Ronnie O\'Brien',
    u'Ronnie O\u2019Brien': 'Ronnie O\'Brien',
    'Keiran O\'brien': 'Keiran O\'Brien',
    'Neil Mcnab': 'Neil McNab',
    'Jason Hern\xe1ndez': 'Jason Hernandez',
    u'J\xe1mison Olave': 'Jamison Olave',
    u'Abraham Fran\xe7ois': 'Abraham Francois',
    'Giuseppe Depalo': 'Giuseppe DePalo',
    'James Dedeus': 'James DeDeus',
    'JP Rodrigues': 'J.P. Rodrigues',
    u'Leo Gonz\xe1lez': 'Leo Gonzalez',
    'John Debrito': 'John DeBrito',
    'Nick Desantis': 'Nick De Santis',
    'Nick DeSantis': 'Nick De Santis',
    'AJ Wood': 'A.J. Wood',
    u'Orlando P\xe9rez': 'Orlando Perez',
    u'Jair Ben\xedtez': 'Jair Benitez',
    'Dave Van den Bergh': 'Dave van den Bergh',
    u'Michael Uma\xf1a': 'Michael Umana',
    u'Rodrigo L\xf3pez': 'Rodrigo Lopez',
    'Daniel (Scott) Ikeda': 'Daniel Ikeda',
    'Daniel "Scott" Ikeda': 'Daniel Ikeda',
    u'St\xe9phane Auvray': 'Stephane Auvray',
    'Demetrius White': 'DeMetrius White',
    'Francisco G\xf3mez': 'Francisco Gomez',
    'Stephen DeRoux': 'Stephen deRoux',
    'Stuart Macrury': 'Stuart MacRury',
    'STUART Macrury': 'Stuart MacRury',
    'Jeff Dimaria': 'Jeff DiMaria',
    'Brandon Mcdonald': 'Brandon McDonald',
    'Peter Van de Ven': 'Peter Van De Ven',
    'Nelson Gonz\xe1lez': 'Nelson Gonzalez',
    'Damarcus Beasley': 'DaMarcus Beasley',
    u'Rafael M\xe1rquez': 'Rafael Marquez',
    'Brett Mcdermott': 'Brett McDermott',
    'Sean Mcauley': 'Sean McAuley',
    'Cristian Da Silva': 'Cristian da Silva',
    'ANDREW Mcdermott': 'Andrew McDermott',
    'Andrew Mcdermott': 'Andrew McDermott',
    'Leighton O\'brien': 'Leighton O\'Brien',
    u'\xc1lvaro Fern\xe1ndez': 'Alvaro Fernandez',
    'Jerome Lee-Yaw': 'Jerome Lee Yaw',
    'Michael* Ueltschey': 'Michael Ueltschey',
    'Danny Devall': 'Danny DeVall',
    'Danilo Da Silva': 'Danilo da Silva',
    'JT Dorsey': 'J.T. Dorsey',
    u'Andr\xe9s Mendoza': 'Andres Mendoza',
    'David Demello': 'David DeMello',
    'Jose Dasilva': 'Jose DaSilva',
    u'Herculez G\xf3mez': 'Herculez Gomez',
    u'Pablo Hern\xe1ndez': 'Pablo Hernandez',
    'Drew Mcathy': 'Drew McAthy',
    'Marvin Ch\xe1vez': 'Marvin Chavez',
    'Quinn O\'sullivan': 'Quinn O\'Sullivan',
    u'Alvaro Sabor\xedo': 'Alvaro Saborio',
    u'\xc1lvaro Sabor\xedo': 'Alvaro Saborio',
    'David De La Torre': 'David de la Torre',
    'Paul Decastro': 'Paul DeCastro',
    u'Claudio Su\xe1rez': 'Claudio Suarez',
    u'Emilio Renter\xeda': 'Emilio Renteria',
    u'Diego Guti\xe9rrez': 'Diego Gutierrez',
    u'Danny O\u2019Rourke': 'Danny O\'Rourke',
    'Joey Disalvo': 'Joey DiSalvo',
    'Joey Digiamarino': 'Joey DiGiamarino',
    'John Diraimondo': 'John DiRaimondo',
    'DJ Countess': 'D.J. Countess',
    'Alex Pineda-Chacon': 'Alex Pineda Chacon',
    'Justin S Hughes': 'Justin S. Hughes',
    'Michael N\'doumbe': 'Michael N\'Doumbe',
    'Jeff Devettori': 'Jeff DeVettori',
    'Jason Ditullio': 'Jason DiTullio',
    u'Juli\xe1n De Guzman': 'Julian De Guzman',
    'Mike DuHaney': 'Mike Duhaney',
    'Dedi Ben-Dayan': 'Dedi Ben Dayan',
    'David Diplacido': 'David DiPlacido',
    u'Jos\xe9 Cancela': 'Jose Cancela',
    u'\xa0Jose Cancela': 'Jose Cancela',
    u'Fabi\xe1n Esp\xedndola': 'Fabian Espindola',
    'Kevin O\'brien': 'Kevin O\'Brien',
    'Isaias Bardales Jr': 'Isaias Bardales Jr.',
    'Nino Da Silva': 'Nino da Silva',
    'Antonio De Avila': 'Antonio de Avila',
    'Jose Burciaga Jr': 'Jose Burciaga Jr.',
    u'Christian G\xf3mez': 'Christian Gomez',
    'Paul O\'donnell': 'Paul O\'Donnell',
    'Gary Depalma': 'Gary DePalma',
    u'S\xe9bastien Le Toux': 'Sebastien Le Toux',
    'Rachid El Khalifi': 'Rachid el Khalifi',
    'Jonathan Mccurley': 'Jonathan McCurley',
    'Brad Mcglaughlin': 'Brad McGlaughlin',
    u'Daniel Hern\xe1ndez': 'Daniel Hernandez',
    u'Milton Rodr\xedguez': 'Milton Rodriguez',
    'JOHN Mccallion': 'John McCallion',
    'John Mccallion': 'John McCallion',
    'Andy Mcmahon': 'Andy McMahon',
    'Francois (Didier) Menard': 'Francois Didier Menard',
    'Anthony Mckeon': 'Anthony McKeon',
    u'O\u2019Brian White': 'O\'Brian White',
    u'Andr\xe9 Luiz': 'Andre Luiz',
    'Kwame Watson Siriboe': 'Kwame Watson-Siriboe',
    'Ivan Mckinley': 'Ivan McKinley',
    'Jim St Andre': 'Jim St. Andre',
    'Hong Myung Bo': 'Hong Myung-Bo',
    u'Juan Diego Gonz\xe1lez': 'Juan Diego Gonzalez',
    u'Ram\xf3n S\xe1nchez': 'Ramon Sanchez',
    'Patrick Mcsorely': 'Patrick McSorely',
    'Steve* Shak': 'Steve Shak',
    'Robert Diguardi': 'Robert DiGuardi',
    'Fred Degand': 'Fred DeGand',
    'CJ Brown': 'C.J. Brown',
    'AJ DeLaGarza': 'A.J. DeLaGarza',
    'Luis Angel Land\xedn': 'Luis Angel Landin',
    u'\xc1lvaro S\xe1nchez': 'Alvaro Sanchez',
    'David Ditomasso': 'David DiTomasso',
    'O\'neil Peart' :'O\'Neil Peart',
    'MICHAEL Mcfarland': 'Michael McFarland',
    'Michael Mcfarland': 'Michael McFarland',
    'Mckinley Tennyson': 'McKinley Tennyson',
    'Peter Lowry.': 'Peter Lowry',
    'Jean-Philippe Peguero': 'Jean Philippe Peguero',
    'Raimo De Vries': 'Raimo de Vries',
    'Chris Mcdonald': 'Chris McDonald',
    'Jan Van Bevern': 'Jan Van Beveren',
    'Thomas W. Cahill': 'Thomas Cahill',
    'Bora Milutinovic': 'Bora Milutinović',
    'Kim Roentved': 'Kim Røntved',


}


def get_name(name, league=None):
    name = name.strip()
    if league and (name, league) in names:
        name = names[(name, league)]
        return get_name(name, league)

    if name in names:
        return get_name(names[name])
    return name
